## Ankur Patel
## ankur.patel@ebscorp.us

In [167]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "https://cdn-images-1.medium.com/fit/t/1600/480/1*KzSyurAkoy2xr1RecfChvA.png", width=800, height=100)

### Many banks and big companies are migrating their legacy codes into Python from VBA, Excel, and SQL.

In [168]:
# pandas can help automate many Excel and SQL tasks
import pandas as pd

In [169]:
# test if the python kernel is working
print ('hello')

hello


In [170]:
# ^ is an or command
# semicolon to declare two variables in same line
a = 5; b = 7
c = 8; d = 4
if a < b ^ c > d:
    print('Made it')

Made it


In [171]:
# | is and command 
a = 5; b = 7
c = 8; d = 4
if (a < b) | (c > d):
    print('Made it')

Made it


In [172]:
# & is also and command 
a = 5; b = 7
c = 8; d = 4
if (a < b) & (c > d):
    print('Made it')

Made it


In [173]:
# range of 4 values
range(4)

range(0, 4)

In [174]:
# list of values in that range
list(range(4))

[0, 1, 2, 3]

In [175]:
# prints the range values in each iteration
for i in range(4):
    print(i)

0
1
2
3


In [176]:
# Iterate with for loops and if condition 
# for loop nested in anther for loop and an if condition
# when j is greater than i, the loop breaks
for i in range(4):
    for j in range(4):
        if j > i:
            break
        print((i, j))

(0, 0)
(1, 0)
(1, 1)
(2, 0)
(2, 1)
(2, 2)
(3, 0)
(3, 1)
(3, 2)
(3, 3)


In [177]:
# variable of obj as series of range with decimal (datatype float)
# setting index values as letters
import pandas as pd
import numpy as np
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [178]:
# value of index b
obj['b']

1.0

In [179]:
# value of index 1
obj[1]

1.0

In [180]:
# values of index 2 and 3
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [181]:
# values of multiple index
# example of shuffling the index
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [182]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [183]:
# puzzle
obj[obj] < 2

0.0    False
1.0    False
2.0    False
3.0    False
dtype: bool

In [184]:
obj[obj]

0.0   NaN
1.0   NaN
2.0   NaN
3.0   NaN
dtype: float64

In [185]:
# only object < 2 
# greater than sign inside the square backets
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [186]:
# defined a list of 4 integers
xlist = [1,2,3,4]
xlist

[1, 2, 3, 4]

In [187]:
# print the elements in that list by iterating
for x in xlist:
    print (x)

1
2
3
4


In [188]:
# define dictionary, curly brackets
# equivalent to json 
xdict = {'x':1, 'y':2}

In [189]:
xdict

{'x': 1, 'y': 2}

In [190]:
# list of a range from 1 to 20 in intervals of 2
list(range(1, 20, 2))


[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [250]:
# dictionary with keys as string defined with values as list 
data = {'state': ['Ujjain', 'Ujjain', 'Ujjain', 'Prayag', 'Prayag', 'Prayag'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}


In [251]:
type(data)

dict

In [252]:
# converting dictionary to dataframe 
# key become column name and list becomes column values
frame = pd.DataFrame(data)
frame

state  year  pop
0  Ujjain  2000  1.5
1  Ujjain  2001  1.7
2  Ujjain  2002  3.6
3  Prayag  2001  2.4
4  Prayag  2002  2.9
5  Prayag  2003  3.2

In [253]:
# datatype of columns in frame
frame.dtypes

state     object
year       int64
pop      float64
dtype: object

In [254]:
# type of data in frame
type(frame)

pandas.core.frame.DataFrame

In [255]:
# data key of state defined to list of values
data['state']
# select state from data;

['Ujjain', 'Ujjain', 'Ujjain', 'Prayag', 'Prayag', 'Prayag']

In [197]:
#Series of state
frame['state']

0    Ujjain
1    Ujjain
2    Ujjain
3    Prayag
4    Prayag
5    Prayag
Name: state, dtype: object

In [198]:
# select state from frame dataframe;
frame[['state']]

state
0  Ujjain
1  Ujjain
2  Ujjain
3  Prayag
4  Prayag
5  Prayag

In [199]:
# optics tells us which is series or frame
# need two square backets for dataframe
print(type(frame['state']))
print(type(frame[['state']]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>


In [200]:
type(data)

dict

In [201]:
# call column names
frame.columns

Index(['state', 'year', 'pop'], dtype='object')

In [202]:
pd.DataFrame(data, columns=['year', 'state'])
# select only a few columns from dict using columns

year   state
0  2000  Ujjain
1  2001  Ujjain
2  2002  Ujjain
3  2001  Prayag
4  2002  Prayag
5  2003  Prayag

In [256]:
# defining index explicitly and pointing to new column to new column that doesnt exist in dictionary
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four',
                             'five', 'six'])
frame2


year   state  pop debt
one    2000  Ujjain  1.5  NaN
two    2001  Ujjain  1.7  NaN
three  2002  Ujjain  3.6  NaN
four   2001  Prayag  2.4  NaN
five   2002  Prayag  2.9  NaN
six    2003  Prayag  3.2  NaN

In [247]:
# title of the columns
# datatype is object, and you convert to list
frame2.columns


Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [257]:
frame2[['state']]
# dataframe columns are lists

state
one    Ujjain
two    Ujjain
three  Ujjain
four   Prayag
five   Prayag
six    Prayag

In [206]:
frame2.index
# index rows of dataframe, datatype is object

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [259]:
frame2['debt'] = 16.5
# giving new empty column a value of 16.5

In [260]:
frame2

year   state  pop  debt
one    2000  Ujjain  1.5  16.5
two    2001  Ujjain  1.7  16.5
three  2002  Ujjain  3.6  16.5
four   2001  Prayag  2.4  16.5
five   2002  Prayag  2.9  16.5
six    2003  Prayag  3.2  16.5

In [209]:
pd.DataFrame(frame2.debt)
# debt column in frame2 dataframe

debt
one    16.5
two    16.5
three  16.5
four   16.5
five   16.5
six    16.5

In [210]:
frame2[['debt']]
# debt column in frame2 dataframe

debt
one    16.5
two    16.5
three  16.5
four   16.5
five   16.5
six    16.5

In [211]:
frame2.loc[['three']]
# loc for index of three

year   state  pop  debt
three  2002  Ujjain  3.6  16.5

In [212]:
frame2.iloc[[2]]
# iloc for particular index

year   state  pop  debt
three  2002  Ujjain  3.6  16.5

In [263]:
frame2.iloc[2,3]
# can give particular values in the index

16.5

In [213]:
frame2.iloc[:2,:3]

year   state  pop
one  2000  Ujjain  1.5
two  2001  Ujjain  1.7

In [214]:
frame2['debt'] = np.arange(6)
frame2
# redefining the debt column with a range of 6 integers

year   state  pop  debt
one    2000  Ujjain  1.5     0
two    2001  Ujjain  1.7     1
three  2002  Ujjain  3.6     2
four   2001  Prayag  2.4     3
five   2002  Prayag  2.9     4
six    2003  Prayag  3.2     5

In [215]:
np.arange(6)
# first 6 integers

array([0, 1, 2, 3, 4, 5])

In [267]:
frame.T.T
#Tranpose

state  year  pop
0  Ujjain  2000  1.5
1  Ujjain  2001  1.7
2  Ujjain  2002  3.6
3  Prayag  2001  2.4
4  Prayag  2002  2.9
5  Prayag  2003  3.2

In [268]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ujjain', 'Kashi', 'Prayag'])
# dataframe with 9 integers in shape of 3 cols 3 rows, index names of a b c, and column names 

In [269]:
frame

Ujjain  Kashi  Prayag
a       0      1       2
c       3      4       5
d       6      7       8

In [271]:
np.arange(9).reshape((3, 3))
# 9 values 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [219]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2
# reindex to add an index 

Ujjain  Kashi  Prayag
a     0.0    1.0     2.0
b     NaN    NaN     NaN
c     3.0    4.0     5.0
d     6.0    7.0     8.0

In [275]:
states = ['Ujjain', 'Kashi', 'Mathura']
# change state 'Prayag' to 'Mathura'

In [276]:
frame.reindex(columns=states)
# no list of Mathura, similar to debt column earlier

Ujjain  Kashi  Mathura
a       0      1      NaN
c       3      4      NaN
d       6      7      NaN

In [222]:
frame.loc[['a', 'b', 'c', 'd'], states]
# index of a b c d rows, states columns 

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  """Entry point for launching an IPython kernel.


Ujjain  Kashi  Mathura
a     0.0    1.0      NaN
b     NaN    NaN      NaN
c     3.0    4.0      NaN
d     6.0    7.0      NaN

In [279]:
import warnings
warnings.filterwarnings("ignore")

frame.loc[['a', 'b', 'c', 'd'], states]

Ujjain  Kashi  Mathura
a     0.0    1.0      NaN
b     NaN    NaN      NaN
c     3.0    4.0      NaN
d     6.0    7.0      NaN

In [223]:
frame.iloc[[0,1,2], [0,1,2]]
# specific rows and columns

Ujjain  Kashi  Prayag
a       0      1       2
c       3      4       5
d       6      7       8

In [224]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ujjain', 'Kashi', 'Prayag', 'Rameshwar'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ujjain       0    1      2     3
Kashi        4    5      6     7
Prayag       8    9     10    11
Rameshwar   12   13     14    15

In [280]:
np.arange(16).reshape((2, 8))
# not defining 

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [226]:
data

one  two  three  four
Ujjain       0    1      2     3
Kashi        4    5      6     7
Prayag       8    9     10    11
Rameshwar   12   13     14    15

In [227]:
data[data['three'] > 5]
# select * from data where column three values > 5;

one  two  three  four
Kashi        4    5      6     7
Prayag       8    9     10    11
Rameshwar   12   13     14    15

In [228]:
data[ data < 5]
# values in data < 5

one  two  three  four
Ujjain     0.0  1.0    2.0   3.0
Kashi      4.0  NaN    NaN   NaN
Prayag     NaN  NaN    NaN   NaN
Rameshwar  NaN  NaN    NaN   NaN

In [229]:
data['three'] > 5
# checking which values in three column are > 5

Ujjain       False
Kashi         True
Prayag        True
Rameshwar     True
Name: three, dtype: bool

In [230]:
data>5
# checking which values in data are > 5

one    two  three   four
Ujjain     False  False  False  False
Kashi      False  False   True   True
Prayag      True   True   True   True
Rameshwar   True   True   True   True

In [231]:
data.iloc[:3, :3]
# specific selection of rows and columns

one  two  three
Ujjain    0    1      2
Kashi     4    5      6
Prayag    8    9     10

In [232]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
# df1 of 9 floats, df2 of 2 floats

In [233]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [234]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [235]:
df1+df2
# 

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [283]:
frame.apply(lambda x: x.max(), axis = 1)
# applying lambda function to frame 
# max of each index

a    2
c    5
d    8
dtype: int64

In [237]:
frame

Ujjain  Kashi  Prayag
a       0      1       2
c       3      4       5
d       6      7       8

In [238]:
frame.apply(lambda x: x.max(), axis =0)
# axis 0 is columns, axis 1 is row index

Ujjain    6
Kashi     7
Prayag    8
dtype: int64

In [284]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3], [4, 5]],
                  index=['a', 'b', 'c', 'd','e'],
                  columns=['one', 'two'])
df
# dataframe with rows, naming row and column indexes 

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3
e  4.00  5.0

In [285]:
df.sum(axis =1)
# 

a    1.40
b    2.60
c    0.00
d   -0.55
e    9.00
dtype: float64

In [241]:
pd.DataFrame(df.sum(axis =1))
# axis = 1 rows

0
a  1.40
b  2.60
c  0.00
d -0.55

In [292]:
df.sum()
# default axis is column

one      13.25
two      -0.80
sumax    12.45
dtype: float64

In [290]:
df['sumax'] = df.sum(axis='columns')
df
# by rows 

one  two  sumax
a  1.40  NaN   1.40
b  7.10 -4.5   2.60
c   NaN  NaN   0.00
d  0.75 -1.3  -0.55
e  4.00  5.0   9.00

In [244]:
df.describe()
# statistics of the columns

one       two     sumax
count  3.000000  2.000000  4.000000
mean   3.083333 -2.900000  1.725000
std    3.493685  2.262742  2.839454
min    0.750000 -4.500000 -1.100000
25%    1.075000 -3.700000 -0.275000
50%    1.400000 -2.900000  1.400000
75%    4.250000 -2.100000  3.400000
max    7.100000 -1.300000  5.200000